# Generated by Django 5.1.1 on 2024-09-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentojuridico',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Documento Jurídico', 'verbose_name_plural': 'Documentos Jurídicos'},
        ),
        migrations.AddField(
            model_name='documentojuridico',
            name='descricao_fatos',
            field=models.TextField(default='ND', verbose_name='Descrição dos Fatos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentojuridico',
            name='juizo_competente',
            field=models.CharField(default='ND', max_length=255, verbose_name='Juízo Competente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentojuridico',
            name='tipo_acao',
            field=models.CharField(default=1, max_length=255, verbose_name='Tipo de Ação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentojuridico',
            name='valor_causa',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Valor da Causa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentojuridico',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo do Documento'),
        ),
        migrations.AlterField(
            model_name='documentojuridico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='documentojuridico',
            name='tipo',
            field=models.CharField(choices=[('peticao_inicial', 'Petição Inicial'), ('contestacao', 'Contestação')], default='peticao_inicial', max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='documentojuridico',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título do Documento'),
        ),
    ]
