# Generated by Django 5.1.1 on 2024-09-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documentojuridico_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmentaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50)),
                ('orgao_julgador', models.CharField(blank=True, max_length=255, null=True)),
                ('ministro_relator', models.CharField(blank=True, max_length=255, null=True)),
                ('data_julgamento', models.DateField(blank=True, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('referencias_legais', models.TextField(blank=True, null=True)),
                ('ementa', models.TextField()),
                ('palavras_chave', models.TextField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documentos_ementajuridica',
            },
        ),
    ]
