# Generated by Django 5.1.1 on 2024-09-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_ementajuridica_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ementajuridica',
            name='user',
        ),
    ]
