# Generated by Django 5.1.1 on 2024-09-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_documentojuridico_anexo_documentojuridico_provas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentojuridico',
            name='processo_numero',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do Processo'),
        ),
    ]
