# Generated by Django 5.1.1 on 2024-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_alter_documentojuridico_descricao_fatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentojuridico',
            name='justica_gratis',
            field=models.BooleanField(default=False),
        ),
    ]
