# Generated by Django 5.1.2 on 2024-10-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_documentojuridico_justica_gratis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentojuridico',
            name='justica_gratis',
            field=models.BooleanField(default=False, verbose_name='Adicionar pedido de justiça grátis'),
        ),
    ]
