# Generated by Django 5.1.2 on 2024-10-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_alter_documentojuridico_justica_gratis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentojuridico',
            name='tipo',
            field=models.CharField(choices=[('peticao_inicial', 'Petição Inicial'), ('contestacao', 'Contestação'), ('apelacao', 'Apelação'), ('embargos', 'Embargos'), ('recurso_extraordinario', 'Recurso Extraordinário')], default='peticao_inicial', max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
